title: Denmoth Hub
description: Advanced Minecraft Modding
url: "https://denmoth.pp.ua"


remote_theme: just-the-docs/just-the-docs


color_scheme: dark
search_enabled: true
heading_anchors: true


plugins:
  - jekyll-seo-tag


aux_links:
  "GitHub": "https://github.com/Denmoth"


exclude:
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
