title: Denmoth
url: "https://denmoth.pp.ua"
baseurl: ""

languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["assets", "css", "js", "images"]

plugins:
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
plugins_dir: [_plugins]