title: Denmoth Hub
description: Minecraft Modding
url: "https://denmoth.pp.ua"

remote_theme: just-the-docs/just-the-docs

color_scheme: dark
logo: /assets/images/logo.png 
search_enabled: true
heading_anchors: true

aux_links:
  "GitHub": "https://github.com/Denmoth"
  "Discord": "#"

footer_content: "Copyright &copy; 2025 Denmoth. Distributed under MIT License."
