title: Denmoth
email: denmoth8871top@gmail.com
description: >-
  Minecraft Mods & Tools
baseurl: ""
url: "https://denmoth.pp.ua"
future: true
permalink: pretty
markdown: kramdown
theme: jekyll-theme-primer

languages: ["en", "ru"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "assets"]

parallel_localization: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-polyglot
