title: Denmoth
email: your-email@example.com
description: >-
  Minecraft Mods & Tools
baseurl: ""
url: "https://denmoth.pp.ua"
permalink: pretty
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
